baseURL = 'https://camillebrl.github.io/'
languageCode = 'en-us'
title = 'My Blog'
paginate = 5
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[languages.en]
    languageName = "English"
    weight = 1

    [languages.en.taxonomies]
        category = "categories"
        tag = "tags"
        series = "series"

    [[languages.en.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10

    [[languages.en.menu.main]]
    name = "Archive"
    url = "archives"
    weight = 5

    [[languages.en.menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 10

    [[languages.en.menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/camille-barboule-353829147/"
    weight = 6

    [[languages.en.menu.main]]
        name = "Twitter"
        url = "https://twitter.com/BarbouleCamille"
        weight = 7

[params]
    env = 'production'
    description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author = 'Theme PaperMod'
    defaultTheme = 'auto'
    ShowReadingTime = true
    ShowToc = true
    TocOpen = true
    ShowShareButtons = false
    ShowBreadCrumbs = true

    [params.label]
        icon = "paresseux.png"
        iconHeight = 25
 
    [params.profileMode]
        enabled = false
        title = "PaperMod"
        imageUrl = "#"
        imageTitle = "my image"

        [[params.profileMode.buttons]]
            name = "Archives"
            url = "archives"

        [[params.profileMode.buttons]]
            name = "Tags"
            url = "tags"

    [params.homeInfoParams]
        title = "Welcome to my blog ! "