baseURL = 'https://camillebrl.github.io/'
languageCode = 'en-us'
title = 'My Blog'
paginate = 5
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[languages.en]
    languageName = "English"
    weight = 1

    [languages.en.taxonomies]
        category = "categories"
        tag = "tags"
        series = "series"
        theme = "theme"
        subtheme = "subtheme

    [[languages.en.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10

    [[languages.en.menu.main]]
    name = "Archive"
    url = "archives"
    weight = 5

    [[languages.en.menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 10

    [[languages.en.menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/camille-barboule-353829147/"
    weight = 6

    [[languages.en.menu.main]]
        name = "Twitter"
        url = "https://twitter.com/BarbouleCamille"
        weight = 7

[taxonomies]
category = "categories"
theme = "theme"
subtheme = "subtheme"

[[menu.main]]
name = "Implementation Tutorials"
url = "/content/implementation_tutorials/"
weight = 10

[[menu.main]]
name = "Paper Review"
url = "/content/paper_review/"
weight = 20

[[menu.main]]
name = "My Researches"
url = "/content/my_researches/"
weight = 30

[params]
    env = 'production'
    description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author = 'Theme PaperMod'
    defaultTheme = 'auto'
    ShowReadingTime = true
    ShowToc = true
    TocOpen = true
    ShowShareButtons = false
    ShowBreadCrumbs = true

    [params.label]
        icon = "paresseux.png"
        iconHeight = 25
 
    [params.profileMode]
        enabled = false
        title = "PaperMod"
        imageUrl = "#"
        imageTitle = "my image"

        [[params.profileMode.buttons]]
            name = "Archives"
            url = "archives"

        [[params.profileMode.buttons]]
            name = "Tags"
            url = "tags"

    [params.homeInfoParams]
        title = "Welcome to my blog ! "
    
    [[params.homeSections]]
    title = "Implementation Tutorials"
    description = "Explore our collection of detailed tutorials that guide you through the implementation of various projects and concepts. These tutorials provide step-by-step instructions to help you learn and build."
    category = "implementation_tutorials"

    [[params.homeSections]]
    title = "Paper Review"
    description = "Dive into in-depth reviews of research papers, academic studies, and scholarly articles. My paper reviews offer insights and summaries of academic papers"
    category = "paper_review"

    [[params.homeSections]]
    title = "My Researches"
    description = "Discover my ongoing research projects and findings. This section offers a glimpse into my academic and scientific pursuits, covering a wide range of topics and investigations."
    category = "my_researches"